# Generated by Django 4.0.5 on 2022-12-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(blank=True, max_length=50)),
                ('product_name', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('slug', models.CharField(blank=True, max_length=50)),
                ('Stock_inicial', models.CharField(blank=True, max_length=50)),
                ('entradas', models.CharField(blank=True, max_length=50)),
                ('price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
