# Generated by Django 4.0.5 on 2022-11-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
